version: '3.3'

services:
  ecos_picture_image:
    build:
      context: .
      target: production
    container_name: ecos_picture_image_container
    image: johedotcom/ecos-image-repository:latest
    restart: always
    ports:
      - "0.0.0.0:4050:4000" 
    volumes:
      - .:/usr/src/app
    command: ["node", "dist/main.js"]
    networks:
      - ecos_network

networks:
  ecos_network:
    external: true