version: '3.3'

services:
  ecos_backend_image:
    build:
      context: .
      target: production
    container_name: ecos_backend
    image: johedotcom/ecos-backend-repository:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://root:Ph@mNgocH4n@postgres_database_server_container:5432/db_ecos
      - IMAGE_SERVER_ENDPOINT=http://ecos.joheee.com:4050
    ports:
      - '0.0.0.0:4040:3000'
    volumes:
      - .:/usr/src/app
    command: ['node', 'dist/main.js']
    networks:
      - ecos_network
      - pg_network

networks:
  ecos_network:
    external: true
  pg_network:
    external: true

